:- module(solve_equation_expert, [expert_solve/3, expert_capabilities/1]).
:- use_module(prolog/zeals).

%% Generated by ZEALS.
%% Problem and plan metadata are embedded for traceability.
generated_problem(solve_equation).
generated_plan(sequence([analyse(problem(solve_equation)),collect_components,fallback([verify(independent_verifier,method(undefined_expression_detector)),verify(independent_verifier,method(linear_equation_solver)),verify(independent_verifier,method(generated_solve_equation_5)),verify(independent_verifier,method(generated_solve_equation_4)),verify(independent_verifier,method(generated_solve_equation_3)),verify(independent_verifier,method(generated_solve_equation_2)),verify(independent_verifier,method(generated_solve_equation_1)),verify(independent_verifier,method(constant_evaluator)),fail_with(unknown,reason(no_applicable_verified_method))])])).

expert_solve(Input, Result, Explanation) :-
    generated_problem(ProblemId),
    zeals:zeals_run(ProblemId, Input, Result),
    Explanation = explanation{problem: ProblemId, result: Result}.

expert_capabilities(Capabilities) :-
    generated_problem(ProblemId),
    zeals:get_capabilities(ProblemId, Capabilities).
