:- module(sample_problem_expert, [expert_solve/3, expert_capabilities/1]).
:- use_module(prolog/zeals).

%% Generated by ZEALS.
%% Problem and plan metadata are embedded for traceability.
generated_problem(sample_problem).
generated_plan(sequence([analyse(problem(sample_problem)),collect_components,fallback([verify(independent_verifier,method(square_solver)),verify(independent_verifier,method(unsupported_guard)),fail_with(unknown,reason(no_applicable_verified_method))])])).

expert_solve(Input, Result, Explanation) :-
    generated_problem(ProblemId),
    zeals:zeals_run(ProblemId, Input, Result),
    Explanation = explanation{problem: ProblemId, result: Result}.

expert_capabilities(Capabilities) :-
    generated_problem(ProblemId),
    zeals:get_capabilities(ProblemId, Capabilities).
