:- module(zeals_emit, [
    emit_expert_module/4
]).

:- use_module(library(option)).

emit_expert_module(ProblemId, Plan, File, Options) :-
    option(module_name(ModuleName), Options, generated_zeals_expert),
    option(include_comments(IncludeComments), Options, true),
    open(File, write, Stream),
    format(Stream, ':- module(~q, [expert_solve/3, expert_capabilities/1]).~n', [ModuleName]),
    format(Stream, ':- use_module(prolog/zeals).~n~n', []),
    maybe_write_comment(Stream, IncludeComments, 'Generated by ZEALS.'),
    maybe_write_comment(Stream, IncludeComments, 'Problem and plan metadata are embedded for traceability.'),
    format(Stream, 'generated_problem(~q).~n', [ProblemId]),
    format(Stream, 'generated_plan(~q).~n~n', [Plan]),
    format(Stream, 'expert_solve(Input, Result, Explanation) :-~n', []),
    format(Stream, '    generated_problem(ProblemId),~n', []),
    format(Stream, '    zeals:zeals_run(ProblemId, Input, Result),~n', []),
    format(Stream, '    Explanation = explanation{problem: ProblemId, result: Result}.~n~n', []),
    format(Stream, 'expert_capabilities(Capabilities) :-~n', []),
    format(Stream, '    generated_problem(ProblemId),~n', []),
    format(Stream, '    zeals:get_capabilities(ProblemId, Capabilities).~n', []),
    close(Stream),
    load_files(File, [silent(true), if(changed), imports([])]).

maybe_write_comment(_Stream, false, _Comment) :- !.
maybe_write_comment(Stream, true, Comment) :-
    format(Stream, '%% ~w~n', [Comment]).
